const Data = [
  {
    id: 1,
    discount: 50,
    cover: "/assets/chair-1.jpg",
    name: "Shoes",
    price: 100,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: 2,
    discount: 40,
    cover: "/assets/shoe-2.jpg",
    name: "Watch",
    price: 20,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: 3,
    discount: 40,
    cover: "/assets/t-shirt-1.jpg",
    name: "Smart Mobile Black",
    price: 200,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: 4,
    discount: 40,
    cover: "/assets/watch-1.jpg",
    name: "Smart Watch Black",
    price: 50,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: 5,
    discount: 50,
    cover: "/assets/watch-2.jpg",
    name: "Shoes",
    price: 100,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: 6,
    discount: 50,
    cover: "/assets/lamp.jpg",
    name: "Shoes",
    price: 100,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: 7,
    discount: 50,
    cover: "/assets/pant-1.jpg",
    name: "Shoes",
    price: 100,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: 8,
    discount: 50,
    cover: "/assets/plant-combo.jpg",
    name: "Shoes",
    price: 100,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: 9,
    discount: 50,
    cover: "/assets/plant-1.jpg",
    name: "Shoes",
    price: 100,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: 10,
    discount: 50,
    cover: "/assets/shoe-3.jpg",
    name: "Shoes",
    price: 100,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },{
    id: 11,
    discount: 50,
    cover: "/assets/headphone-1.jpg",
    name: "Shoes",
    price: 100,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },{
    id: 12,
    discount: 50,
    cover: "/assets/chair-2.jpg",
    name: "Shoes",
    price: 100,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },{
    id: 13,
    discount: 50,
    cover: "/assets/jacket-1.jpg",
    name: "Shoes",
    price: 100,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: 14,
    discount: 50,
    cover: "/assets/t-shirt-2.jpg",
    name: "Shoes",
    price: 100,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },{
    id: 15,
    discount: 50,
    cover: "/assets/top.jpg",
    name: "Shoes",
    price: 100,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
];
export default Data;
